In [1]:
import numpy as np

## 3-D Array

In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,12,13]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 12 13]]]


## ndim Attribute
    returns the dimension of an array

In [6]:
print(f"Dimension: {arr.ndim}")

Dimension: 3


## ndmin Argument
    when creating an array we can define the dimension using ndmin argument

In [7]:
arr1=np.array([1,2,3,4,5], ndmin=3)
print(arr1)
print(f"Dimension: {arr1.ndim}")

[[[1 2 3 4 5]]]
Dimension: 3


## Accessing array elements


### Accessing 1-D arrays

In [13]:
arr2=np.array([1,2,3,4,5])
print(arr2[1])
print(arr2[3])

2
4


### Accessing 2-D arrays

In [18]:
arr3=np.array([[1,2,3,4],[5,6,7,9]])
print(arr3)
print(arr3[0,2])
print(arr3[1,3])

[[1 2 3 4]
 [5 6 7 9]]
3
9


### Accessing 3-D arrays

In [22]:
arr4=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr4[0,0,2])
print(arr4[1,0,1])
print(arr4[-1,-2,-1])

3
8
9


## Slicing of arrays
    [start:end:step] or [start:end]
        includes the start index but excludes the end index

In [45]:
print(arr4)
print('\n')
print(arr4[0:1,0:1,:-1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[[1 2]]]


In [46]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[::2])

[10 20 30 40]


## Converting data types in existing array
    The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
    dtype attribute returns the data type of the array

In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

## The Difference Between Copy and View
    * The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
    * The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not     affect the copy.
    * The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [49]:
arr=np.array([1,2,3,4,5])
newarr=arr.copy()
print(newarr)
newarr[2]=0
print(newarr)
print(arr)

[1 2 3 4 5]
[1 2 0 4 5]
[1 2 3 4 5]


In [51]:
newarr=arr.view()
print(newarr)
newarr[2]=0
print(newarr)
print(arr)

[1 2 3 4 5]
[1 2 0 4 5]
[1 2 0 4 5]


##
Every NumPy array has the attribute base that returns None if the array owns the data.

In [52]:
newarr=arr.copy()
oldarr=arr.view()

print(newarr.base)
print(oldarr.base)

None
[1 2 0 4 5]


## Shape of an array
    It is the number of elements in each dimension.
    shape argument returns a tuple.
    each index of the tuple contains the number of corresponding elements. 

In [54]:
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])

print(arr.shape)

(1, 2, 4)


## Reshaping arrays
    By reshaing we can add or remove dimensions or change the number of elements in a dimension.

In [59]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr.reshape(5,2))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


#### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [68]:
arr=np.array([[[1,2,3,4],[9,7,8,10]]])
print(arr.reshape(2,2,-1))

[[[ 1  2]
  [ 3  4]]

 [[ 9  7]
  [ 8 10]]]


#### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [70]:
print(arr)
print(arr.reshape(-1))

[[[ 1  2  3  4]
  [ 9  7  8 10]]]
[ 1  2  3  4  9  7  8 10]


In NumPy, flatten() and ravel() are two methods used to convert a multi-dimensional array into a 1D array (also known as "flattening" the array).

The flatten() method returns a new copy of the array, always creating a new 1D array with the same data, but it does not affect the original array.

The ravel() method, unlike flatten(), returns a flattened view of the original array whenever possible. This means it doesn't create a copy if the array is contiguous in memory, and changes to the returned ravel array may modify the original array.

In [77]:
newarr=arr.ravel()
print(arr)
print(newarr)
newarr[3]=10
print(arr)

[[1 2 3 4]
 [4 5 6 7]]
[1 2 3 4 4 5 6 7]
[[ 1  2  3 10]
 [ 4  5  6  7]]


In [76]:
arr=np.array([[1,2,3,4],[4,5,6,7]])
print(arr)
print(arr.flatten())

[[1 2 3 4]
 [4 5 6 7]]
[1 2 3 4 4 5 6 7]


## Iterating Arrays Using nditer()
    The function nditer() is a helping function that can be used from very basic to very advanced iterations.
    In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [84]:
print(arr)
for x in np.nditer(arr):
    print(x, end=' ')

[[ 1  2  3 10]
 [ 4  5  6  7]]
1 2 3 10 4 5 6 7 